/**
 * THE ALSO-TIER WRITE GATE, DRIVEN END TO END.
 *
 * Decision `portee-et-mode-ecriture-des-vaults` (2026-09-04), Phase 3 of
 * `portee-ergonomie-refus-roadmap`. `tests/vault-reach.test.mjs` proves
 * `alsoWriteTierFor` / `assertVaultWritable` in isolation, and
 * `tests/index-internals.test.mjs` proves the dispatcher predicate
 * `requiresAlsoTierCheck` as a pure function — both stay green if the
 * `CallTool` handler never actually calls them. This file is the other half:
 * it spawns the real `bin/obsidian-mcp-router.mjs`, speaks MCP over its
 * stdio, and drives real `tools/call` requests against a workspace bound to a
 * primary vault with three kinds of secondary — writable, locked, soft — plus
 * the two traps the decision names by number:
 *
 *   - trap 2: the first-contact conformance repair (itself proven in
 *     isolation by `tests/vault-conformance-e2e.test.mjs`) must not write to
 *     a locked or soft-tier secondary even on a plain READ.
 *   - trap 3: `confirm_workspace_binding` must stay able to NAME a vault the
 *     also-tier gate would otherwise refuse to write to — the gate applies to
 *     write TOOLS, never to the binding tool itself.
 *
 * The harness is the one `tests/audit-middleware-e2e.test.mjs` established
 * and `tests/vault-conformance-e2e.test.mjs` reuses: a loopback stand-in for
 * the Local REST API, in-process, so the router's real request/response cycle
 * runs without a real vault on disk.
 */

import { test, describe, after } from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import http from 'node:http';
import { spawn } from 'node:child_process';
import { fileURLToPath } from 'node:url';

import { SEARCH_INDEX_PATH } from '../src/helpers/bm25-index.mjs';
import { canonicalWorkspaceKey } from '../src/helpers/workspace-bindings.mjs';
import { homeSafeEnv } from './_home-safe-spawn.mjs';

const REPO = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const BIN = path.join(REPO, 'bin', 'obsidian-mcp-router.mjs');
const API_KEY = 'also-tier-e2e-key';

const tmpDirs = [];
after(() => {
  for (const d of tmpDirs) { try { fs.rmSync(d, { recursive: true, force: true }); } catch { /* best effort */ } }
});

/** Same loopback stand-in `vault-conformance-e2e.test.mjs` uses — see there for the request-record shape. */
async function startFakeVault(files) {
  const store = new Map(Object.entries(files));
  const seen = [];
  const server = http.createServer((req, res) => {
    let body = '';
    req.setEncoding('utf8');
    req.on('data', (c) => { body += c; });
    req.on('end', () => {
      const url = decodeURIComponent(req.url);
      seen.push({ method: req.method, url, body });
      if (url === '/') {
        res.writeHead(200, { 'Content-Type': 'application/json' });
        res.end(JSON.stringify({ status: 'OK' }));
        return;
      }
      const rel = url.replace(/^\/vault\//, '');
      if (req.method === 'PUT') {
        store.set(rel, body);
        res.writeHead(204).end();
        return;
      }
      if (req.method === 'DELETE') {
        store.delete(rel);
        res.writeHead(204).end();
        return;
      }
      if (rel.endsWith('/') || rel === '') {
        const prefix = rel;
        const names = new Set();
        for (const p of store.keys()) {
          if (!p.startsWith(prefix)) continue;
          const rest = p.slice(prefix.length);
          const slash = rest.indexOf('/');
          names.add(slash === -1 ? rest : `${rest.slice(0, slash)}/`);
        }
        if (names.size === 0) { res.writeHead(404).end('not found'); return; }
        res.writeHead(200, { 'Content-Type': 'application/json' });
        res.end(JSON.stringify({ files: [...names].sort() }));
        return;
      }
      if (!store.has(rel)) { res.writeHead(404).end('not found'); return; }
      res.writeHead(200, { 'Content-Type': 'text/markdown' });
      res.end(store.get(rel));
    });
  });
  await new Promise((r) => server.listen(0, '127.0.0.1', r));
  return {
    seen,
    store,
    port: server.address().port,
    close: () => new Promise((r) => server.close(r)),
  };
}

/** A drifted-but-valid vault, same shape `vault-conformance-e2e.test.mjs` uses, so first-contact has something to repair. */
const DRIFTED = {
  'wiki-meta/catalog.md': '---\ntype: index\ntitle: "Wiki Catalog"\n---\n\n# Wiki Catalog\n',
  'wiki/index.md':
    "---\nokf_version: '0.1'\n---\n\n# v\n\n> Generated by obsidian-mcp-router — index de navigation généré.\n\n# Subdirectories\n\n* [notes](notes/index.md) - Contains 1 document\n",
  'wiki/log.md':
    '# Update Log\n\n> Generated by obsidian-mcp-router — index de navigation généré.\n\n## 2026-07-01\n\n* **Created**: [Alpha](notes/alpha.md)\n',
  'wiki/notes/index.md':
    '# Note\n\n> Generated by obsidian-mcp-router — index de navigation généré.\n\n* [Alpha](alpha.md) - Desc Alpha\n',
  'wiki/notes/alpha.md':
    '---\ntype: note\ntitle: "Alpha"\ndescription: "Desc Alpha"\ncreated: 2026-07-01\n---\n\nUn corps avec des mots discriminants: hydrolienne, marmotte.\n',
};

/**
 * A workspace bound to `work` (primary) with `writable-ref` / `locked-ref` /
 * `soft-ref` as secondaries — the three write tiers plus the primary, all
 * pointed at the SAME fake vault server (vault identity is the router's own
 * bookkeeping; the underlying store does not need to differ per name for
 * these tests, which only ask "did a write reach the server at all").
 */
function writeConfig(port, { vaultReach } = {}) {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'also-tier-e2e-'));
  tmpDirs.push(dir);
  const configPath = path.join(dir, 'config.json');
  const baseUrl = `http://127.0.0.1:${port}`;
  const remote = (name) => ({ name, baseUrl, apiKey: API_KEY, timeoutMs: 5000 });
  const key = canonicalWorkspaceKey(dir);
  fs.writeFileSync(configPath, JSON.stringify({
    portRegistry: {},
    vaultNames: {},
    remoteVaults: [
      remote('work'),
      remote('writable-ref'),
      remote('locked-ref'),
      remote('soft-ref'),
    ],
    defaultVault: 'work',
    alsoWritable: ['writable-ref'],
    alsoLocked: ['locked-ref'],
    ...(vaultReach ? { vaultReach: 'declared', openVaults: [] } : {}),
    workspaceBindings: {
      [key]: {
        vault: 'work',
        also: ['writable-ref', 'locked-ref', 'soft-ref'],
        locked: false,
        confirmedAt: '2026-09-05',
        confirmedVia: 'test',
      },
    },
  }, null, 2), 'utf8');
  return { dir, configPath };
}

function startRouter({ configPath, cwd, env = {} }) {
  const child = spawn(process.execPath, [BIN, '--config', configPath], {
    cwd,
    env: homeSafeEnv(cwd, {
      OBSIDIAN_ROUTER_NO_WATCH: '1',
      MD_ALLOWED_PATHS: cwd,
      OBSIDIAN_ROUTER_LOCKED: '',
      OBSIDIAN_ROUTER_VIEW_AGENT_URL: '',
      OBSIDIAN_ROUTER_USER_ID: '',
      ...env,
    }),
    stdio: ['pipe', 'pipe', 'pipe'],
  });
  let stdout = '';
  let stderr = '';
  const waiters = new Map();
  child.stdout.setEncoding('utf8');
  child.stderr.setEncoding('utf8');
  child.stderr.on('data', (c) => { stderr += c; });
  child.stdout.on('data', (chunk) => {
    stdout += chunk;
    let nl;
    while ((nl = stdout.indexOf('\n')) !== -1) {
      const raw = stdout.slice(0, nl).trim();
      stdout = stdout.slice(nl + 1);
      if (!raw) continue;
      let msg;
      try { msg = JSON.parse(raw); } catch { continue; }
      const w = waiters.get(msg.id);
      if (w) { waiters.delete(msg.id); w(msg); }
    }
  });
  const send = (msg) => child.stdin.write(`${JSON.stringify(msg)}\n`);
  const call = (id, method, params) => new Promise((resolve, reject) => {
    const timer = setTimeout(
      () => reject(new Error(`timed out waiting for ${method}\n--- router stderr ---\n${stderr}`)),
      20000,
    );
    waiters.set(id, (m) => { clearTimeout(timer); resolve(m); });
    send({ jsonrpc: '2.0', id, method, params });
  });
  return { child, call, send, stderrText: () => stderr, kill: () => child.kill() };
}

async function handshake(rt) {
  await rt.call(1, 'initialize', {
    protocolVersion: '2024-11-05',
    capabilities: {},
    clientInfo: { name: 'also-tier-e2e', version: '0' },
  });
  rt.send({ jsonrpc: '2.0', method: 'notifications/initialized' });
}

/** The write-related PUTs a `write_file` call would have made (excludes conformance's own index/projection writes). */
function contentPuts(vault, relPath) {
  return vault.seen.filter((r) => r.method === 'PUT' && r.url === `/vault/${relPath}`);
}

async function waitForIndexWrite(vault, { timeoutMs = 8000 } = {}) {
  const deadline = Date.now() + timeoutMs;
  while (Date.now() < deadline) {
    if (vault.seen.some((r) => r.method === 'PUT' && r.url === `/vault/${SEARCH_INDEX_PATH}`)) return true;
    await new Promise((r) => setTimeout(r, 50));
  }
  return false;
}

describe('E2E: the also-tier write gate, for a workspace bound to work + 3 secondaries', () => {
  test('a write to the PRIMARY vault is never gated', async () => {
    const vault = await startFakeVault(DRIFTED);
    const { dir, configPath } = writeConfig(vault.port);
    const rt = startRouter({ configPath, cwd: dir });
    try {
      await handshake(rt);
      const res = await rt.call(2, 'tools/call', {
        name: 'write_file',
        arguments: { vault: 'work', path: 'wiki/notes/new.md', content: '# New\n' },
      });
      assert.ok(!res.error && !res.result?.isError, `primary write failed: ${JSON.stringify(res.error || res.result)}\n${rt.stderrText()}`);
      assert.equal(contentPuts(vault, 'wiki/notes/new.md').length, 1);
    } finally {
      rt.kill();
      await vault.close();
    }
  });

  test('a write to an alsoWritable secondary succeeds with NO confirmSecondaryWrite needed', async () => {
    const vault = await startFakeVault(DRIFTED);
    const { dir, configPath } = writeConfig(vault.port);
    const rt = startRouter({ configPath, cwd: dir });
    try {
      await handshake(rt);
      const res = await rt.call(2, 'tools/call', {
        name: 'write_file',
        arguments: { vault: 'writable-ref', path: 'wiki/notes/new.md', content: '# New\n' },
      });
      assert.ok(!res.error && !res.result?.isError, `alsoWritable write failed: ${JSON.stringify(res.error || res.result)}\n${rt.stderrText()}`);
      assert.equal(contentPuts(vault, 'wiki/notes/new.md').length, 1);
    } finally {
      rt.kill();
      await vault.close();
    }
  });

  test('a write to an alsoLocked secondary is refused, EVEN WITH confirmSecondaryWrite: true', async () => {
    const vault = await startFakeVault(DRIFTED);
    const { dir, configPath } = writeConfig(vault.port);
    const rt = startRouter({ configPath, cwd: dir });
    try {
      await handshake(rt);
      const res = await rt.call(2, 'tools/call', {
        name: 'write_file',
        arguments: { vault: 'locked-ref', path: 'wiki/notes/new.md', content: '# New\n', confirmSecondaryWrite: true },
      });
      const text = res.result?.content?.[0]?.text ?? '';
      assert.ok(res.result?.isError || /Error/.test(text), `expected a refusal, got: ${JSON.stringify(res.error || res.result)}`);
      assert.match(text, /locked read-only/);
      assert.equal(contentPuts(vault, 'wiki/notes/new.md').length, 0, 'no write must have reached the vault');
    } finally {
      rt.kill();
      await vault.close();
    }
  });

  test('a write to the default (soft-tier) secondary is refused WITHOUT confirmation', async () => {
    const vault = await startFakeVault(DRIFTED);
    const { dir, configPath } = writeConfig(vault.port);
    const rt = startRouter({ configPath, cwd: dir });
    try {
      await handshake(rt);
      const res = await rt.call(2, 'tools/call', {
        name: 'write_file',
        arguments: { vault: 'soft-ref', path: 'wiki/notes/new.md', content: '# New\n' },
      });
      const text = res.result?.content?.[0]?.text ?? '';
      assert.ok(res.result?.isError || /Error/.test(text), `expected a refusal, got: ${JSON.stringify(res.error || res.result)}`);
      assert.match(text, /SECONDARY vault/);
      assert.match(text, /confirmSecondaryWrite/);
      assert.equal(contentPuts(vault, 'wiki/notes/new.md').length, 0);
    } finally {
      rt.kill();
      await vault.close();
    }
  });

  test('a write to the soft-tier secondary succeeds WHEN confirmSecondaryWrite: true is passed', async () => {
    const vault = await startFakeVault(DRIFTED);
    const { dir, configPath } = writeConfig(vault.port);
    const rt = startRouter({ configPath, cwd: dir });
    try {
      await handshake(rt);
      const res = await rt.call(2, 'tools/call', {
        name: 'write_file',
        arguments: { vault: 'soft-ref', path: 'wiki/notes/new.md', content: '# New\n', confirmSecondaryWrite: true },
      });
      assert.ok(!res.error && !res.result?.isError, `confirmed soft-tier write failed: ${JSON.stringify(res.error || res.result)}\n${rt.stderrText()}`);
      assert.equal(contentPuts(vault, 'wiki/notes/new.md').length, 1);
    } finally {
      rt.kill();
      await vault.close();
    }
  });

  test('write_bundle: a RUN-mode recovery (an operation id + confirm:true) on an alsoLocked secondary is refused BEFORE it can replay anything', async () => {
    // Regression for a defect the adversarial review caught: the also-tier
    // gate's write_bundle exemption originally used `isRecoveryCall`, which
    // does not distinguish the READ-ONLY listing mode (`recover: true`) from
    // the RUN mode (`recover: "<operationId>"`, which WRITES via
    // rollbackPaths) — so a RUN-mode call bypassed `alsoLocked`'s own
    // advertised "no exceptions" guarantee entirely. The gate must now refuse
    // it exactly like any other write, whether or not a journal for that
    // operation id actually exists — the refusal happens before the handler
    // (and its own journal lookup) ever runs.
    const vault = await startFakeVault(DRIFTED);
    const { dir, configPath } = writeConfig(vault.port);
    const rt = startRouter({ configPath, cwd: dir });
    try {
      await handshake(rt);
      const res = await rt.call(2, 'tools/call', {
        name: 'write_bundle',
        arguments: { vault: 'locked-ref', recover: 'op-0000000000000000', confirm: true },
      });
      const text = res.result?.content?.[0]?.text ?? '';
      assert.ok(res.result?.isError || /Error/.test(text), `expected a refusal, got: ${JSON.stringify(res.error || res.result)}`);
      assert.match(text, /locked read-only/);
    } finally {
      rt.kill();
      await vault.close();
    }
  });

  test('write_bundle: the READ-ONLY recovery listing (recover: true) on an alsoLocked secondary is NOT refused by the also-tier gate', async () => {
    const vault = await startFakeVault(DRIFTED);
    const { dir, configPath } = writeConfig(vault.port);
    const rt = startRouter({ configPath, cwd: dir });
    try {
      await handshake(rt);
      const res = await rt.call(2, 'tools/call', {
        name: 'write_bundle',
        arguments: { vault: 'locked-ref', recover: true },
      });
      const text = res.result?.content?.[0]?.text ?? '';
      assert.ok(!res.error && !res.result?.isError, `the read-only listing must not be refused by the write gate: ${JSON.stringify(res.error || res.result)}\n${rt.stderrText()}`);
      assert.ok(!/locked read-only/.test(text));
    } finally {
      rt.kill();
      await vault.close();
    }
  });
});

/**
 * Regression coverage for the P1 finding TWO INDEPENDENT Codex review passes
 * converged on: the also-tier gate correctly let a preview/dry-run call
 * through (nothing to check — it writes nothing), but the audit log and the
 * debounced projections/search-index scheduler further down the SAME
 * dispatcher still keyed off `WRITE_TOOL_NAMES.has(name)` alone — which is
 * true for `delete_file`/`write_bundle` REGARDLESS of `preview` — so a
 * "read-only" preview against an `alsoLocked` secondary still produced a
 * real write (an audit-journal append, a scheduled maintenance refresh).
 * Fixed by `toolActuallyWrote`, consulted by both blocks instead.
 */
describe('E2E: preview/dry-run calls must not trigger post-write middleware on an alsoLocked secondary', () => {
  test('delete_file preview:true on a locked secondary appends NO audit entry, even with OBSIDIAN_ROUTER_USER_ID set', async () => {
    const vault = await startFakeVault(DRIFTED);
    const { dir, configPath } = writeConfig(vault.port);
    const rt = startRouter({ configPath, cwd: dir, env: { OBSIDIAN_ROUTER_USER_ID: 'reviewer' } });
    try {
      await handshake(rt);
      const res = await rt.call(2, 'tools/call', {
        name: 'delete_file',
        arguments: { vault: 'locked-ref', path: 'wiki/notes/alpha.md', preview: true },
      });
      assert.ok(!res.error && !res.result?.isError, `the preview itself failed: ${JSON.stringify(res.error || res.result)}\n${rt.stderrText()}`);
      // Give the (fire-and-forget) audit + projections middleware a moment —
      // if either fired, its PUT would already be recorded by now.
      await new Promise((r) => setTimeout(r, 800));
      assert.deepEqual(
        vault.seen.filter((r) => r.method === 'PUT' || r.method === 'DELETE').map((r) => r.url), [],
        'a delete_file PREVIEW must never write to an alsoLocked vault — not the deleted file, not an audit entry, not a projections refresh',
      );
    } finally {
      rt.kill();
      await vault.close();
    }
  });

  test('write_bundle preview:true (an ordinary apply preview, not a recovery) on a locked secondary appends NO audit entry', async () => {
    const vault = await startFakeVault(DRIFTED);
    const { dir, configPath } = writeConfig(vault.port);
    const rt = startRouter({ configPath, cwd: dir, env: { OBSIDIAN_ROUTER_USER_ID: 'reviewer' } });
    try {
      await handshake(rt);
      const res = await rt.call(2, 'tools/call', {
        name: 'write_bundle',
        arguments: {
          vault: 'locked-ref',
          preview: true,
          steps: [{ op: 'write', path: 'wiki/notes/new.md', content: '# New\n' }],
        },
      });
      assert.ok(!res.error && !res.result?.isError, `the preview itself failed: ${JSON.stringify(res.error || res.result)}\n${rt.stderrText()}`);
      await new Promise((r) => setTimeout(r, 800));
      assert.deepEqual(
        vault.seen.filter((r) => r.method === 'PUT' || r.method === 'DELETE').map((r) => r.url), [],
        'a write_bundle PREVIEW must never write to an alsoLocked vault',
      );
    } finally {
      rt.kill();
      await vault.close();
    }
  });

  test('control: a REAL (non-preview) write to the alsoWritable secondary DOES append an audit entry', async () => {
    // The other half of the claim: this fix must not have silently turned
    // audit logging off for genuine writes.
    const vault = await startFakeVault(DRIFTED);
    const { dir, configPath } = writeConfig(vault.port);
    const rt = startRouter({ configPath, cwd: dir, env: { OBSIDIAN_ROUTER_USER_ID: 'reviewer' } });
    try {
      await handshake(rt);
      const res = await rt.call(2, 'tools/call', {
        name: 'write_file',
        arguments: { vault: 'writable-ref', path: 'wiki/notes/new.md', content: '# New\n' },
      });
      assert.ok(!res.error && !res.result?.isError, `the write itself failed: ${JSON.stringify(res.error || res.result)}\n${rt.stderrText()}`);
      await new Promise((r) => setTimeout(r, 800));
      const journalPuts = vault.seen.filter((r) => r.method === 'PUT' && /journal\.md|log\.md/.test(r.url));
      assert.ok(journalPuts.length >= 1, `a real write must still be audited: ${JSON.stringify(vault.seen.map((r) => `${r.method} ${r.url}`))}`);
    } finally {
      rt.kill();
      await vault.close();
    }
  });
});

describe('E2E: trap 2 — first contact never repairs a locked or soft-tier secondary', () => {
  test('a plain READ on the soft-tier secondary does NOT trigger the search-index repair', async () => {
    const vault = await startFakeVault(DRIFTED);
    const { dir, configPath } = writeConfig(vault.port);
    const rt = startRouter({ configPath, cwd: dir });
    try {
      await handshake(rt);
      const res = await rt.call(2, 'tools/call', {
        name: 'get_file',
        arguments: { vault: 'soft-ref', path: 'wiki/notes/alpha.md' },
      });
      assert.ok(!res.error, `the read itself failed: ${JSON.stringify(res.error)}\n${rt.stderrText()}`);
      await new Promise((r) => setTimeout(r, 800));
      assert.deepEqual(
        vault.seen.filter((r) => r.method === 'PUT').map((r) => r.url), [],
        'a soft-tier secondary must never be repaired by a mere read',
      );
    } finally {
      rt.kill();
      await vault.close();
    }
  });

  test('a plain READ on the alsoLocked secondary does NOT trigger the search-index repair', async () => {
    const vault = await startFakeVault(DRIFTED);
    const { dir, configPath } = writeConfig(vault.port);
    const rt = startRouter({ configPath, cwd: dir });
    try {
      await handshake(rt);
      const res = await rt.call(2, 'tools/call', {
        name: 'get_file',
        arguments: { vault: 'locked-ref', path: 'wiki/notes/alpha.md' },
      });
      assert.ok(!res.error, `the read itself failed: ${JSON.stringify(res.error)}\n${rt.stderrText()}`);
      await new Promise((r) => setTimeout(r, 800));
      assert.deepEqual(
        vault.seen.filter((r) => r.method === 'PUT').map((r) => r.url), [],
        'an alsoLocked secondary must never be repaired by a mere read',
      );
    } finally {
      rt.kill();
      await vault.close();
    }
  });

  test('control: a plain READ on the PRIMARY vault DOES trigger the repair (the exemption is narrow, not the repair being off)', async () => {
    const vault = await startFakeVault(DRIFTED);
    const { dir, configPath } = writeConfig(vault.port);
    const rt = startRouter({ configPath, cwd: dir });
    try {
      await handshake(rt);
      const res = await rt.call(2, 'tools/call', {
        name: 'get_file',
        arguments: { vault: 'work', path: 'wiki/notes/alpha.md' },
      });
      assert.ok(!res.error, `the read itself failed: ${JSON.stringify(res.error)}\n${rt.stderrText()}`);
      assert.ok(
        await waitForIndexWrite(vault),
        'fixture sanity: the primary vault must still get first-contact repaired',
      );
    } finally {
      rt.kill();
      await vault.close();
    }
  });

  test('control: a plain READ on the alsoWritable secondary DOES trigger the repair', async () => {
    const vault = await startFakeVault(DRIFTED);
    const { dir, configPath } = writeConfig(vault.port);
    const rt = startRouter({ configPath, cwd: dir });
    try {
      await handshake(rt);
      const res = await rt.call(2, 'tools/call', {
        name: 'get_file',
        arguments: { vault: 'writable-ref', path: 'wiki/notes/alpha.md' },
      });
      assert.ok(!res.error, `the read itself failed: ${JSON.stringify(res.error)}\n${rt.stderrText()}`);
      assert.ok(
        await waitForIndexWrite(vault),
        'an alsoWritable secondary must be repaired like any other addressable vault',
      );
    } finally {
      rt.kill();
      await vault.close();
    }
  });
});

describe('E2E: trap 3 — confirm_workspace_binding stays able to NAME a vault the reachability gate would refuse', () => {
  test('binding to a vault not yet reachable (vaultReach: "declared", not in openVaults, not yet in any binding) succeeds', async () => {
    const vault = await startFakeVault(DRIFTED);
    const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'also-tier-e2e-trap3-'));
    tmpDirs.push(dir);
    const configPath = path.join(dir, 'config.json');
    const baseUrl = `http://127.0.0.1:${vault.port}`;
    // No workspaceBindings entry at all: this workspace starts with NO binding,
    // so with vaultReach: "declared" and empty openVaults, EVERY vault
    // (including 'target') is unreachable through resolveVault — the exact
    // condition trap 3 says the binding tool must not be subject to.
    fs.writeFileSync(configPath, JSON.stringify({
      portRegistry: {},
      vaultNames: {},
      remoteVaults: [{ name: 'target', baseUrl, apiKey: API_KEY, timeoutMs: 5000 }],
      defaultVault: 'target',
      vaultReach: 'declared',
      openVaults: [],
    }, null, 2), 'utf8');
    const rt = startRouter({ configPath, cwd: dir });
    try {
      await handshake(rt);

      // Sanity: a WRITE tool naming the same vault is refused by the
      // reachability gate right now — proving the fixture actually exercises
      // the guard trap 3 says the binding tool must be exempt from.
      const blocked = await rt.call(2, 'tools/call', {
        name: 'get_file',
        arguments: { vault: 'target', path: 'wiki/notes/alpha.md' },
      });
      const blockedText = blocked.result?.content?.[0]?.text ?? '';
      assert.ok(
        blocked.result?.isError || /not reachable from this workspace/.test(blockedText),
        `fixture sanity: "target" must be unreachable before binding — got ${JSON.stringify(blocked.error || blocked.result)}`,
      );

      const res = await rt.call(3, 'tools/call', {
        name: 'confirm_workspace_binding',
        arguments: { vault: 'target', open: false },
      });
      assert.ok(
        !res.error && !res.result?.isError,
        `confirm_workspace_binding refused an unreachable-but-registered vault: ${JSON.stringify(res.error || res.result)}\n${rt.stderrText()}`,
      );
      const parsed = JSON.parse(res.result.content[0].text);
      assert.equal(parsed.boundTo, 'target');

      // And now that the binding names it, it resolves — the gate reads the
      // LIVE binding, not a snapshot taken at start-up.
      const after = await rt.call(4, 'tools/call', {
        name: 'get_file',
        arguments: { vault: 'target', path: 'wiki/notes/alpha.md' },
      });
      assert.ok(!after.error && !after.result?.isError, `"target" still unreachable after binding: ${JSON.stringify(after.error || after.result)}`);
    } finally {
      rt.kill();
      await vault.close();
    }
  });
});

/**
 * Regression coverage for the adversarial review's most severe finding: the
 * `vault: "*"` fan-out in `search`/`search_smart` read `registry.vaults`
 * directly, bypassing `resolveVault()` entirely — so `vaultReach: "declared"`
 * stopped `search({vault: "roland"})` but not `search({vault: "*"})`, which
 * still read (and returned) content from every registered vault regardless
 * of reachability. Fixed by filtering fan-out candidates through
 * `isVaultReachable` — the same guard `resolveVault()` applies to a named
 * vault — before either tool ever contacts them.
 */
function writeReachabilityConfig(port) {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'also-tier-e2e-fanout-'));
  tmpDirs.push(dir);
  const configPath = path.join(dir, 'config.json');
  const baseUrl = `http://127.0.0.1:${port}`;
  const remote = (name) => ({ name, baseUrl, apiKey: API_KEY, timeoutMs: 5000 });
  const key = canonicalWorkspaceKey(dir);
  fs.writeFileSync(configPath, JSON.stringify({
    portRegistry: {},
    vaultNames: {},
    remoteVaults: [remote('work'), remote('secret')],
    defaultVault: 'work',
    vaultReach: 'declared',
    openVaults: [],
    workspaceBindings: {
      [key]: { vault: 'work', also: [], locked: false, confirmedAt: '2026-09-05', confirmedVia: 'test' },
    },
  }, null, 2), 'utf8');
  return { dir, configPath };
}

describe('E2E: fan-out reachability — vault: "*" must not bypass vaultReach: "declared"', () => {
  test('search({vault:"*"}) excludes a vault this workspace cannot reach', async () => {
    const vault = await startFakeVault(DRIFTED);
    const { dir, configPath } = writeReachabilityConfig(vault.port);
    const rt = startRouter({ configPath, cwd: dir });
    try {
      await handshake(rt);
      const res = await rt.call(2, 'tools/call', {
        name: 'search',
        arguments: { vault: '*', query: 'hydrolienne' },
      });
      assert.ok(!res.error && !res.result?.isError, `fan-out search failed: ${JSON.stringify(res.error || res.result)}\n${rt.stderrText()}`);
      const parsed = JSON.parse(res.result.content[0].text);
      const named = parsed.perVault.map((r) => r.vault);
      assert.ok(named.includes('work'), `the reachable primary must still be included: ${JSON.stringify(named)}`);
      assert.ok(!named.includes('secret'), `an unreachable vault must not appear in the fan-out at all: ${JSON.stringify(named)}`);
    } finally {
      rt.kill();
      await vault.close();
    }
  });

  test('search_smart({vault:"*"}) excludes a vault this workspace cannot reach', async () => {
    const vault = await startFakeVault(DRIFTED);
    const { dir, configPath } = writeReachabilityConfig(vault.port);
    const rt = startRouter({ configPath, cwd: dir });
    try {
      await handshake(rt);
      const res = await rt.call(2, 'tools/call', {
        name: 'search_smart',
        arguments: { vault: '*', query: 'hydrolienne', tier: 'local' },
      });
      assert.ok(!res.error && !res.result?.isError, `fan-out search_smart failed: ${JSON.stringify(res.error || res.result)}\n${rt.stderrText()}`);
      const parsed = JSON.parse(res.result.content[0].text);
      const named = parsed.perVault.map((r) => r.vault);
      assert.ok(named.includes('work'), `the reachable primary must still be included: ${JSON.stringify(named)}`);
      assert.ok(!named.includes('secret'), `an unreachable vault must not appear in the fan-out at all: ${JSON.stringify(named)}`);
    } finally {
      rt.kill();
      await vault.close();
    }
  });
});

describe('E2E: lock_vault refuses to lock to a vault this workspace cannot reach', () => {
  test('lock_vault on an unreachable vault is refused, not applied then bricking every subsequent call', async () => {
    const vault = await startFakeVault(DRIFTED);
    const { dir, configPath } = writeReachabilityConfig(vault.port);
    const rt = startRouter({ configPath, cwd: dir });
    try {
      await handshake(rt);
      const res = await rt.call(2, 'tools/call', {
        name: 'lock_vault',
        arguments: { vault: 'secret' },
      });
      const text = res.result?.content?.[0]?.text ?? '';
      assert.ok(res.result?.isError || /Error/.test(text), `expected a refusal, got: ${JSON.stringify(res.error || res.result)}`);
      assert.match(text, /not reachable from this workspace/);

      // And the session is NOT bricked: a call to the reachable primary
      // still works, proving the lock was never actually applied.
      const after = await rt.call(3, 'tools/call', {
        name: 'get_file',
        arguments: { vault: 'work', path: 'wiki/notes/alpha.md' },
      });
      assert.ok(!after.error && !after.result?.isError, `the session must not be bricked after a refused lock: ${JSON.stringify(after.error || after.result)}`);
    } finally {
      rt.kill();
      await vault.close();
    }
  });
});
