/**
 * Tests for src/helpers/reserved-path-write.mjs — the F3-b conditional writer.
 *
 * The security property under test is NON-DESTRUCTION: on the automatic path,
 * foreign content on a reserved path is never lost without a recoverable copy.
 * Every case is driven behaviourally (assert on the store + the returned
 * backup path), never on "was primitive X called".
 */

import { test, describe } from 'node:test';
import assert from 'node:assert/strict';

import {
  applyReservedWrite,
  applyReservedWrites,
  writeUniqueBackup,
  reservedBackupName,
  isReservedBackupPath,
  RESERVED_BACKUP_INFIX,
  PROTECTION_MODES,
} from '../src/helpers/reserved-path-write.mjs';
import { contentSha256 } from '../src/helpers/content-hash.mjs';

/**
 * An in-memory vault with a REAL cooperative-CAS fake, plus knobs to force the
 * CAS route unusable and to inject a foreign file at a chosen moment.
 */
function makeDeps(files = {}, { casRouteUnusable = false, casStatus = 404 } = {}) {
  const store = new Map(Object.entries(files));
  const writes = [];
  const casCalls = [];
  const deps = {
    getFileContent: async (_v, p) => {
      if (!store.has(p)) throw Object.assign(new Error('404'), { kind: 'not_found' });
      return store.get(p);
    },
    writeFile: async (_v, p, content, opts = {}) => {
      if (opts.applyIfContentPreexists === false && store.has(p)) {
        throw Object.assign(new Error('409'), { kind: 'conflict', status: 409 });
      }
      store.set(p, content);
      writes.push({ path: p, content, opts });
    },
    attemptAtomicCas: async (_v, p, content, expectedSha) => {
      casCalls.push({ path: p, expectedSha });
      if (casRouteUnusable) return { routeUnusable: true, status: casStatus };
      const current = store.has(p) ? store.get(p) : null;
      if (current === null) {
        throw Object.assign(new Error('target-missing'), { kind: 'conflict', status: 409 });
      }
      if (contentSha256(current) !== expectedSha) {
        throw Object.assign(new Error('content-changed'), { kind: 'conflict', status: 409 });
      }
      store.set(p, content);
      return { ok: true };
    },
  };
  return { store, writes, casCalls, deps };
}

const OURS = (title) => `# ${title}\n\n> Generated by obsidian-mcp-router — projection.\n`;
const isOursProjection = (c) => /^> Generated by obsidian-mcp-router/m.test(c);

// ---------------------------------------------------------------------------
// CREATE (path absent at snapshot)
// ---------------------------------------------------------------------------

describe('create-if-absent (snapshot absent)', () => {
  test('a free path is created with the native conditional header', async () => {
    const { store, writes, deps } = makeDeps();
    const out = await applyReservedWrite({
      deps, vault: { name: 'v' }, path: 'wiki/a/index.md', content: OURS('A'),
      snapshotContent: undefined, isOurs: isOursProjection, mode: 'reduced', nowMs: 1,
    });
    assert.equal(out.written, true);
    assert.equal(out.conflict, false);
    assert.equal(writes[0].opts.applyIfContentPreexists, false, 'must use create-only-if-absent');
    assert.equal(store.get('wiki/a/index.md'), OURS('A'));
  });

  test('a file that APPEARED in the window is refused — foreign file byte-intact', async () => {
    const foreign = '# human note\n\nnot yours\n';
    const { store, deps } = makeDeps({ 'wiki/a/index.md': foreign });
    const out = await applyReservedWrite({
      deps, vault: { name: 'v' }, path: 'wiki/a/index.md', content: OURS('A'),
      snapshotContent: undefined, isOurs: isOursProjection, mode: 'reduced', nowMs: 1,
    });
    assert.equal(out.written, false, 'must NOT overwrite');
    assert.equal(out.conflict, true);
    assert.equal(out.conflictKind, 'appeared');
    assert.equal(store.get('wiki/a/index.md'), foreign, 'the appeared foreign file must be byte-intact');
  });
});

// ---------------------------------------------------------------------------
// OVERWRITE — cooperative CAS present
// ---------------------------------------------------------------------------

describe('overwrite — atomic-cooperative (bridge CAS present)', () => {
  test('still ours → CAS regenerates, mode atomic-cooperative', async () => {
    const snap = OURS('A');
    const { store, deps } = makeDeps({ 'wiki/a/index.md': snap });
    const out = await applyReservedWrite({
      deps, vault: { name: 'v' }, path: 'wiki/a/index.md', content: OURS('A2'),
      snapshotContent: snap, isOurs: isOursProjection, mode: 'reduced', nowMs: 1,
    });
    assert.equal(out.written, true);
    assert.equal(out.mode, PROTECTION_MODES.ATOMIC);
    assert.equal(store.get('wiki/a/index.md'), OURS('A2'));
  });

  test('foreign appeared → CAS refuses (409) → conflict, foreign byte-intact, NO overwrite', async () => {
    const snap = OURS('A');
    const foreign = '# human\n';
    // snapshotContent is our old projection, but the store now holds foreign.
    const { store, deps } = makeDeps({ 'wiki/a/index.md': foreign });
    await assert.rejects(
      // attemptAtomicCas throws conflict; applyReservedWrite lets it propagate.
      applyReservedWrite({
        deps, vault: { name: 'v' }, path: 'wiki/a/index.md', content: OURS('A2'),
        snapshotContent: snap, isOurs: isOursProjection, mode: 'reduced', nowMs: 1,
      }),
      (err) => err.kind === 'conflict',
    );
    assert.equal(store.get('wiki/a/index.md'), foreign, 'foreign file must be byte-intact');
  });
});

// ---------------------------------------------------------------------------
// OVERWRITE — reduced (no CAS route): NON-DESTRUCTION via backup
// ---------------------------------------------------------------------------

describe('overwrite — reduced-getcompare (no CAS route)', () => {
  test('still ours → regenerate, NO backup (no pollution)', async () => {
    const snap = OURS('A');
    const { store, writes, deps } = makeDeps({ 'wiki/a/index.md': snap }, { casRouteUnusable: true });
    const out = await applyReservedWrite({
      deps, vault: { name: 'v' }, path: 'wiki/a/index.md', content: OURS('A2'),
      snapshotContent: snap, isOurs: isOursProjection, mode: 'reduced', nowMs: 1,
    });
    assert.equal(out.written, true);
    assert.equal(out.backupPath, undefined, 'regenerating our own file must NOT create a .bak');
    assert.equal(writes.filter((w) => isReservedBackupPath(w.path)).length, 0);
    assert.equal(store.get('wiki/a/index.md'), OURS('A2'));
  });

  test('FOREIGN present at the late read → backed up, THEN overwritten (recoverable)', async () => {
    const snap = OURS('A');
    const foreign = '# human note I wrote by hand\n';
    const { store, deps } = makeDeps({ 'wiki/a/index.md': foreign }, { casRouteUnusable: true });
    const out = await applyReservedWrite({
      deps, vault: { name: 'v' }, path: 'wiki/a/index.md', content: OURS('A2'),
      snapshotContent: snap, isOurs: isOursProjection, mode: 'reduced', nowMs: 1700000000000,
    });
    assert.equal(out.written, true, 'reduced mode overwrites (with a backup)');
    assert.ok(out.backupPath, 'a backup path must be reported');
    assert.ok(isReservedBackupPath(out.backupPath));
    assert.equal(store.get(out.backupPath), foreign, 'the foreign content is recoverable from the backup');
    assert.equal(store.get('wiki/a/index.md'), OURS('A2'), 'the projection was regenerated');
  });
});

// ---------------------------------------------------------------------------
// OVERWRITE — strict (no CAS route): skip, never overwrite
// ---------------------------------------------------------------------------

describe('overwrite — skipped-strict (no CAS route, strict opt-in)', () => {
  test('no usable CAS → SKIP the racy overwrite, capacity-conflict, file untouched', async () => {
    const snap = OURS('A');
    const foreign = '# human\n';
    const { store, writes, deps } = makeDeps({ 'wiki/a/index.md': foreign }, { casRouteUnusable: true });
    const out = await applyReservedWrite({
      deps, vault: { name: 'v' }, path: 'wiki/a/index.md', content: OURS('A2'),
      snapshotContent: snap, isOurs: isOursProjection, mode: 'strict', nowMs: 1,
    });
    assert.equal(out.written, false);
    assert.equal(out.conflict, true);
    assert.equal(out.conflictKind, 'capacity');
    assert.equal(out.mode, PROTECTION_MODES.STRICT);
    assert.equal(store.get('wiki/a/index.md'), foreign, 'strict mode never overwrites without CAS');
    assert.deepEqual(writes, [], 'strict mode writes nothing at all');
  });
});

// ---------------------------------------------------------------------------
// Backup uniqueness (the C12 lesson) + exclusion
// ---------------------------------------------------------------------------

describe('backup uniqueness and exclusion', () => {
  test('two backups of the same path at the same instant get DISTINCT names', async () => {
    const { store, deps } = makeDeps({ 'wiki/a/index.md': 'v1' });
    const now = 1700000000000;
    const b1 = await writeUniqueBackup(deps, { name: 'v' }, 'wiki/a/index.md', 'first', now);
    const b2 = await writeUniqueBackup(deps, { name: 'v' }, 'wiki/a/index.md', 'second', now);
    assert.notEqual(b1, b2, 'the same-instant backups must not collide');
    assert.equal(store.get(b1), 'first');
    assert.equal(store.get(b2), 'second', 'the second backup must NOT have overwritten the first');
  });

  test('the backup name is not a markdown file (excluded from the walkers)', () => {
    const name = reservedBackupName('wiki/a/index.md', 1700000000000);
    assert.equal(/\.md$/i.test(name), false, 'a backup must never end in .md');
    assert.ok(name.includes(RESERVED_BACKUP_INFIX));
    assert.ok(isReservedBackupPath(name));
    assert.equal(isReservedBackupPath('wiki/a/index.md'), false);
  });
});

// ---------------------------------------------------------------------------
// THE SUB-INTERVAL (M2) — the LIMIT this proves, not a closure.
//
// A foreign file that lands STRICTLY BETWEEN the late read and the PUT cannot
// be seen by the read, so it is overwritten with NO backup — a dry loss. This
// test documents that irreducible residual by execution, so no future doc can
// claim the window is closed.
// ---------------------------------------------------------------------------

describe('the sub-interval between the late read and the PUT is NOT covered', () => {
  test('a foreign file landing AFTER the read is overwritten with no backup (documented limit)', async () => {
    const snap = OURS('A');
    const { store, deps } = makeDeps({ 'wiki/a/index.md': snap }, { casRouteUnusable: true });
    // Simulate the sub-window: the late read returns OURS, but a sync client
    // writes a foreign file the instant after — so the store holds foreign when
    // the PUT lands.
    const realGet = deps.getFileContent;
    deps.getFileContent = async (v, p) => {
      const value = await realGet(v, p);
      if (p === 'wiki/a/index.md') store.set(p, '# foreign, landed after the read\n');
      return value; // the read still returned OURS
    };

    const out = await applyReservedWrite({
      deps, vault: { name: 'v' }, path: 'wiki/a/index.md', content: OURS('A2'),
      snapshotContent: snap, isOurs: isOursProjection, mode: 'reduced', nowMs: 1,
    });

    assert.equal(out.written, true);
    assert.equal(out.backupPath, undefined, 'the read saw ours, so it could not back up the sub-window write');
    assert.equal(store.get('wiki/a/index.md'), OURS('A2'), 'the foreign sub-window write was overwritten');
    // Prove the loss: no backup anywhere holds the foreign bytes.
    const backups = [...store.keys()].filter(isReservedBackupPath);
    assert.deepEqual(backups, [], 'the sub-window loss is UNRECOVERABLE — this is the documented residual');
  });
});

// ---------------------------------------------------------------------------
// (d) the backup never pollutes the corpus or the projections
// ---------------------------------------------------------------------------

describe('a backup sidecar is excluded from the walkers', () => {
  test('a .bak path is neither wiki content nor a projection', async () => {
    // Import the real predicates the walkers use.
    const { isProjectionPath, isWikiContentPath } = await import('../src/helpers/okf-projections.mjs');
    const bak = reservedBackupName('wiki/notes/index.md', 1700000000000);
    assert.equal(isProjectionPath(bak), false, 'a backup must never be treated as a projection');
    assert.equal(isWikiContentPath(bak), false, 'a backup must never be indexed as content');
    // The BM25/projection walkers only collect files ending in `.md`.
    assert.equal(/\.md$/i.test(bak), false);
  });
});

// ---------------------------------------------------------------------------
// applyReservedWrites — aggregation
// ---------------------------------------------------------------------------

describe('applyReservedWrites — aggregation + protectionMode', () => {
  test('reports written, backups and the weakest protection mode used', async () => {
    const snapB = OURS('B');
    const { store, deps } = makeDeps(
      { 'wiki/b/index.md': '# foreign\n' },
      { casRouteUnusable: true },
    );
    const result = await applyReservedWrites({
      deps,
      vault: { name: 'v' },
      plannedWrites: [
        { path: 'wiki/a/index.md', content: OURS('A'), snapshotContent: undefined, isOurs: isOursProjection },
        { path: 'wiki/b/index.md', content: OURS('B2'), snapshotContent: snapB, isOurs: isOursProjection },
      ],
      mode: 'reduced',
      nowMs: 1700000000000,
    });
    assert.deepEqual(result.written.sort(), ['wiki/a/index.md', 'wiki/b/index.md']);
    assert.equal(result.backups.length, 1, 'the foreign overwrite produced one backup');
    assert.equal(result.backups[0].path, 'wiki/b/index.md');
    assert.equal(result.protectionMode, PROTECTION_MODES.REDUCED);
    assert.ok(result.warnings.some((w) => w.includes('foreign content')));
    // The backup is recoverable and did not pollute the store as an .md.
    assert.equal(store.get(result.backups[0].backupPath), '# foreign\n');
  });

  test('a create-conflict is reported without a write', async () => {
    const { store, deps } = makeDeps({ 'wiki/a/index.md': '# human\n' });
    const result = await applyReservedWrites({
      deps,
      vault: { name: 'v' },
      plannedWrites: [
        { path: 'wiki/a/index.md', content: OURS('A'), snapshotContent: undefined, isOurs: isOursProjection },
      ],
      mode: 'reduced',
      nowMs: 1,
    });
    assert.deepEqual(result.written, []);
    assert.deepEqual(result.conflicts, ['wiki/a/index.md']);
    assert.equal(store.get('wiki/a/index.md'), '# human\n', 'byte-intact');
  });
});
